name: Notify Discord on redepoyl

on:
  push:
    branches: [main]

jobs:
  notify-discord:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Send Discord webhook notification
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          MESSAGE="Deployment triggered on branch main"
          curl -H "Content-Type: application/json" -X POST -d "{\"content\": \"$MESSAGE\"}" $DISCORD_WEBHOOK_URL
